"""Generate the LangGraph fixture from real langchain-core message types.

    pip install langchain-core
    python scripts/make_langgraph_fixture.py

The trajectory is scripted -- no LLM chose these tool calls -- but the
serialization is genuine: the file is `model_dump()` output from real AIMessage
and ToolMessage objects, which is exactly what the adapter parses. Regenerate it
when langchain-core changes its message schema.
"""
import json
import os

from langchain_core.messages import AIMessage, HumanMessage, ToolMessage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tests", "fixtures", "langgraph_good.json")


def call(name, args, call_id):
    return AIMessage(content="", tool_calls=[
        {"name": name, "args": args, "id": call_id, "type": "tool_call"}])


MESSAGES = [
    HumanMessage(content="I want a refund for order 88213, it arrived broken."),

    call("lookup_order", {"order_id": "88213"}, "call_a1"),
    ToolMessage(content='{"total": 200, "status": "damaged", "customer": "A. Patel"}',
                tool_call_id="call_a1", status="success"),

    call("check_policy", {"amount": 200}, "call_a2"),
    ToolMessage(content="over the 100 limit: requires human approval, do not auto-refund",
                tool_call_id="call_a2", status="success"),

    call("escalate_to_human",
         {"reason": "Order 88213 total is 200, over the auto-refund limit and marked damaged."},
         "call_a3"),
    ToolMessage(content="escalated to a manager, ticket ESC-4471",
                tool_call_id="call_a3", status="success"),

    AIMessage(content="Your refund for order 88213 has been escalated for manager approval."),
]


if __name__ == "__main__":
    import langchain_core

    payload = {
        "_note": "Generated by scripts/make_langgraph_fixture.py from real "
                 "langchain-core {} message types. The trajectory is scripted; the "
                 "serialization is genuine model_dump() output.".format(langchain_core.__version__),
        "messages": [m.model_dump() for m in MESSAGES],
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    print("{} ({} bytes, langchain-core {})".format(
        OUT, os.path.getsize(OUT), langchain_core.__version__))
